### ISSUE TITLE
An Exception。。。。

### ISSUE THREAD

**Issue by xiaoxi-note** [sejoker/react-native-android-vitamio#1]
hi,
import  the  module,  run the app,throw exception:
Error while updating property 'color' in shadow node of type:RCTText

**Comment by sejoker** [comment]
@xiaoxi-note thanks for reporting, I will definately take a look.

**Comment by xiaoxi-note** [comment]
@sejoker  can you give me a demo ?....thank you,thank you,thank you....

**Comment by sejoker** [comment]
@xiaoxi-note What version of React Native are you using?

**Comment by xiaoxi-note** [comment]
@sejoker v0.15.0
Is it only work on v0.11.2?

**Comment by sejoker** [comment]
it works with RN up to 0.13. Starting from 0.14, some breaking changes were
introduced for native modules. I am in progress of migrating to 0.14-0.16
versions.

2015-12-08 3:32 GMT+01:00 xiaoxi-note notifications@github.com:

**Comment by xiaoxi-note** [comment]
@sejoker  give me an available project code , , , , thank   you  . ..  
My e-mail :  xiaoxinote@gmail.com

**Comment by sejoker** [comment]
@xiaoxi-note demo app: https://github.com/sejoker/react-native-android-vitamio

**Comment by sejoker** [comment]
updated component to support React Native 0.19
