### ISSUE TITLE
Its crash when install release apk build

### ISSUE THREAD

**Issue by ducchungtx** [sejoker/react-native-android-vitamio#12]
Its crash in both simulator (GENYMOTION (5.1.0)) and real device (Android 5.0). In debug not problem. 

Thanks.

**Comment by sejoker** [comment]
@zrmedia have your resolved your issue or you gave up on the idea to make it work?

**Comment by ducchungtx** [comment]
@sejoker i change in android/build.gradle 
classpath 'com.android.tools.build:gradle:1.3.1' to classpath 'com.android.tools.build:gradle:1.5.0'

Nice project and i hope you can support react-native 0.28+
