### ISSUE TITLE
VitamioView shows blank

### ISSUE THREAD

**Issue by abbasfreestyle** [sejoker/react-native-android-vitamio#5]
The player appears to be blank when using VitamioView

I used the following code:

`import VitamioView from 'react-native-android-vitamio';`
`<VitamioView style={styles.video} streamUrl="rtmp://fms.12E5.edgecastcdn.net/0012E5/mp4:videos/8Juv1MVa-485.mp4"/>`

i noticed in the index.js file the propType name is 'VideoView'

so i also tried like so:
`import VideoView from 'react-native-android-vitamio';`
`<VideoView style={styles.video} streamUrl="rtmp://fms.12E5.edgecastcdn.net/0012E5/mp4:videos/8Juv1MVa-485.mp4"/>`

unfortunately still nothing...

**Comment by sejoker** [comment]
I am on vacation at the moment with terrible internet connection, will back
to you on couple of days.

**Comment by ibraizQazi** [comment]
This aint working for me. It doesn't compile the project completely.
My terminal shows this:
:RNVitamioView:compileReleaseJavaWithJavac
E:\React Projects\VitamioPlayer\node_modules\react-native-android-vitamio\src\ma
in\java\com\RNVitamioView\VitamioViewManager.java:11: error: cannot find symbol
import com.facebook.react.uimanager.annotations.ThemedReactContext;
                                               ^
  symbol:   class ThemedReactContext
  location: package com.facebook.react.uimanager.annotations
E:\React Projects\VitamioPlayer\node_modules\react-native-android-vitamio\src\ma
in\java\com\RNVitamioView\VitamioViewManager.java:26: error: cannot find symbol
    private ThemedReactContext mContext = null;
            ^
  symbol:   class ThemedReactContext
  location: class VitamioViewManager
E:\React Projects\VitamioPlayer\node_modules\react-native-android-vitamio\src\ma
in\java\com\RNVitamioView\VitamioViewManager.java:38: error: cannot find symbol
    public VideoView createViewInstance(ThemedReactContext context) {
                                        ^
  symbol:   class ThemedReactContext
  location: class VitamioViewManager
3 errors
:RNVitamioView:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':RNVitamioView:compileReleaseJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 22.529 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

Any idea how to solve it?

**Comment by sejoker** [comment]
@ibraizQazi the problem with compilation was fixed in [PR](https://github.com/sejoker/react-native-android-vitamio/pull/4). Try to use the latest version

**Comment by ibraizQazi** [comment]
@sejoker I was caught up in a project, i'll try it and get back to you. Thanks
