### ISSUE TITLE
issue with 'Video View' has no proptype for native prop 'RCTVitamioView.testID' of native type 'String'

### ISSUE THREAD

**Issue by sdfrao** [sejoker/react-native-android-vitamio#6]
`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
var VitamioView = require('react-native-android-vitamio');
class app3 extends Component {
  render() {
    return (
      <View style={styles.container}>
        <VitamioView style={styles.video} streamUrl="http://streambe2.nayatel.com/movies1/Deadpool-HD.mp4"/>

```
  </View>
);
```

  }
}
class VideoScreen extends React.Component {
  render() {
    return (
      <View>
      <VitamioView style={styles.video} streamUrl="http://streambe2.nayatel.com/movies1/Deadpool-HD.mp4"/>
       // <VitamioView style={styles.video} streamUrl="rtmp://fms.12E5.edgecastcdn.net/0012E5/mp4:videos/8Juv1MVa-485.mp4"/>
      </View>
    );
  }
}
var styles = StyleSheet.create({

   video: {
      flex: 1,
      flexDirection: 'row',
      height: 400,
    },
});
module.exports = VideoScreen;
AppRegistry.registerComponent('app3', () => app3);`

Edited the file as given in the read me file , then code shows this error "issue with 'Video View' has no propType for native prop 'RCTVitamioView.testID' of native type 'String' ...... after that error, i have updated the both react-native and node.js" .. 
while trying to implement the plugin of vitamio for video view faced many issues but resolved all of them, now unable to resolve that issue" 
adding video view in react native is possible ??
![screenshot_2016-05-06-14-49-20](https://cloud.githubusercontent.com/assets/16952003/15090819/793981d6-144e-11e6-910b-9fd3460508da.png)

**Comment by sejoker** [comment]
@sdfrao please try this solution (add ...View.propTypes):

```
var View = React.View;

var { requireNativeComponent, PropTypes, View } = require('react-native');

var iface = {
  name: 'VideoView',
  propTypes: {
    ...View.propTypes,
    streamUrl: PropTypes.string
  }
};
```
