### ISSUE TITLE
unable to import the vitamio for video view

### ISSUE THREAD

**Issue by sdfrao** [sejoker/react-native-android-vitamio#7]
![annotation](https://cloud.githubusercontent.com/assets/16952003/15105156/b2128580-15d8-11e6-990a-612f252deeb5.png)
**facing issue in the import of VitamioViewManager.java .
kindly help me to resolve the error. By removing annotation from the import..

> import com.facebook.react.uimanager.annotations.ThemedReactContext;
> new issue arise which is 
> ![screenshot_2016-05-06-14-49-20](https://cloud.githubusercontent.com/assets/16952003/15105147/a6f4b61e-15d8-11e6-805b-1c356305c637.png)

 i want to add video in my application.

code of my index.android.js
`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
var VitamioView = require('react-native-android-vitamio');
class app5 extends Component {
  render() {
    return (
      <View style={styles.container}>
         <VitamioView style={styles.video} streamUrl="http://streambe2.nayatel.com/movies1/Deadpool-HD.mp4"/>

```
  </View>
);
```

  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  video: {
      flex: 1,
      flexDirection: 'row',
      height: 400,
    },

});

AppRegistry.registerComponent('app5', () => app5);`
**

**Comment by sejoker** [comment]
it was fixed with this [PR](https://github.com/sejoker/react-native-android-vitamio/pull/4)
