### ISSUE TITLE
VideoView` has no propType for native prop....

### ISSUE THREAD

**Issue by openGeeksLab** [sejoker/react-native-android-vitamio#8]
First , a lot of thanks for this plugin!)
I have an issue:
VideoView`has no propType for native prop`RCTVitamioView.renderToHardwareTextureAndroid`of native type`boolean`
Any ideas?
Thanks

**Comment by sejoker** [comment]
The fix is quite [simple](http://stackoverflow.com/a/34244587/540802):

```
var View = React.View;

var { requireNativeComponent, PropTypes, View } = require('react-native');

var iface = {
  name: 'VideoView',
  propTypes: {
    ...View.propTypes,
    streamUrl: PropTypes.string
  }
};
```

**Comment by openGeeksLab** [comment]
Works!Thanks
